---

on:
  push:
    tags:
    - v*-create-task-runner

jobs:
  publish-create-task-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: ./scripts/build.sh
    - uses: JS-DevTools/npm-publish@v1
      with:
        access: public
        check-version: false
        dry-run: true
        package: ./packages/create-task-runner/package.json
        token: ${{ secrets.NPM_TOKEN }}
